# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-10 19:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='decision',
            name='Applicant',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='decision',
            name='ApplicationNumber',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='decision',
            name='Articles',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='decision',
            name='ECLI',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='decision',
            name='IPC',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='decision',
            name='Keywords',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='decision',
            name='Language',
            field=models.CharField(default='', max_length=2),
        ),
        migrations.AddField(
            model_name='decision',
            name='OnlineDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='decision',
            name='Rules',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='decision',
            name='Text',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='decision',
            name='Board',
            field=models.CharField(default='', max_length=16),
        ),
        migrations.AlterField(
            model_name='decision',
            name='CaseNumber',
            field=models.CharField(default='', max_length=16),
        ),
        migrations.AlterField(
            model_name='decision',
            name='DecisionDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='decision',
            name='Title',
            field=models.TextField(default=''),
        ),
    ]
