# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-10 22:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20160610_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decision',
            name='DecisionDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
