# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-11 19:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20160611_1514'),
    ]

    operations = [
        migrations.RenameField(
            model_name='decision',
            old_name='_DecisionDate',
            new_name='DecisionDate',
        ),
        migrations.RenameField(
            model_name='decision',
            old_name='_Text',
            new_name='FactsAndSubmissions',
        ),
        migrations.RenameField(
            model_name='decision',
            old_name='_OnlineDate',
            new_name='OnlineDate',
        ),
        migrations.AddField(
            model_name='decision',
            name='Order',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='decision',
            name='Reasons',
            field=models.TextField(default=''),
        ),
    ]
