# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-16 22:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20160611_2106'),
    ]

    operations = [
        migrations.AddField(
            model_name='decision',
            name='CitedCases',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='decision',
            name='Distribution',
            field=models.CharField(default='D', max_length=1),
        ),
        migrations.AddField(
            model_name='decision',
            name='Headword',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='decision',
            name='Link',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='decision',
            name='Opponents',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='decision',
            name='PDFLink',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='decision',
            name='TextDownloaded',
            field=models.BooleanField(default=False),
        ),
    ]
