# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-20 18:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20160617_0028'),
    ]

    operations = [
        migrations.AddField(
            model_name='decision',
            name='MetaDownloaded',
            field=models.BooleanField(default=False),
        ),
    ]
