# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-21 19:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20160620_2325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='decision',
            name='FactsAndSubmissions',
        ),
        migrations.RemoveField(
            model_name='decision',
            name='Order',
        ),
        migrations.RemoveField(
            model_name='decision',
            name='Reasons',
        ),
        migrations.AddField(
            model_name='decision',
            name='Appellants',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='decision',
            name='Catchwords',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='decision',
            name='Respondents',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='decision',
            name='Articles',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='decision',
            name='CitedCases',
            field=models.CharField(default='', max_length=700),
        ),
        migrations.AlterField(
            model_name='decision',
            name='Rules',
            field=models.CharField(default='', max_length=100),
        ),
    ]
