# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-21 21:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20160621_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='decision',
            name='HasSplitText',
            field=models.BooleanField(default=False),
        ),
    ]
