# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-21 21:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_decision_hassplittext'),
    ]

    operations = [
        migrations.AddField(
            model_name='decision',
            name='FactsAndSubmissions_DE',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='decision',
            name='FactsAndSubmissions_EN',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='decision',
            name='FactsAndSubmissions_FR',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='decision',
            name='Order_DE',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='decision',
            name='Order_EN',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='decision',
            name='Order_FR',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='decision',
            name='Reasons_DE',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='decision',
            name='Reasons_EN',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='decision',
            name='Reasons_FR',
            field=models.TextField(default=''),
        ),
    ]
