# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-24 22:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20160623_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decision',
            name='DecisionLanguage',
            field=models.CharField(choices=[('DE', 'DE'), ('EN', 'EN'), ('FR', 'FR')], default='', max_length=2),
        ),
        migrations.AlterField(
            model_name='decision',
            name='Link',
            field=models.URLField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='decision',
            name='PDFLink',
            field=models.URLField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='decision',
            name='ProcedureLanguage',
            field=models.CharField(choices=[('DE', 'DE'), ('EN', 'EN'), ('FR', 'FR')], default='', max_length=2),
        ),
    ]
